name: Release
on: workflow_dispatch
jobs:
  build-project:
      strategy:
        matrix:
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.x

        - name: Install PyInstaller
          run: |
            pip install pyinstaller
        - name: Build executable
          run: |
            pyinstaller main.py --onefile -w
            
        - name: Archive output content
          uses: thedoctor0/zip-release@master
          with:
            filename: output.zip
            directory: dist/
            
        - uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.os }}
            path: dist/*.zip
            
  distribute-project:
    name: Distribute project to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - uses: actions/download-artifact@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"
